//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_02.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Bookings = new HashSet<Booking>();
        }

        [Key]
        public int AccountID { get; set; }

        [Required(ErrorMessage = "This Field Is Required To Be Filled.")]
        [Display(Name = "Full Name")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "This Field Is Required To Be Filled.")]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "This Field Is Required To Be Filled.")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string AccountPassword { get; set; }

        [Required(ErrorMessage = "This Field Is Required To Be Filled.")]
        [Display(Name = "Address")]
        public string PersonAddress { get; set; }

        [Required(ErrorMessage = "This Field Is Required To Be Filled.")]
        [Display(Name = "Phone Number")]
        public string PersonPhoneNo { get; set; }

        [Required(ErrorMessage = "This Field Is Required To Be Filled.")]
        [Display(Name = "Gender")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "This Field Is Required To Be Filled.")]
        [Display(Name = "Blood Type")]
        public string BloodType { get; set; }

        [Required(ErrorMessage = "This Field Is Required To Be Filled.")]
        [Display(Name = "Role")]
        public string AccountRole { get; set; }

        [Required(ErrorMessage = "This Field Is Required To Be Filled.")]
        [Display(Name = "Date Of Birth")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DOB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
