//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_02.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        [Key]
        public int BookingID { get; set; }

        [Required(ErrorMessage = "This Field Is Required To Be Filled.")]
        [Display(Name = "Appointment Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> BookingDate { get; set; }

        [Required(ErrorMessage = "This Field Is Required To Be Filled.")]
        [Display(Name = "Appointment Time")]
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> TimeSlot { get; set; }

        //[Required(ErrorMessage = "This Field Is Required To Be Filled.")]
        [Display(Name = "Hospital Department")]
        public string Department { get; set; }

        [Display(Name = "Doctor Name")]
        public string DoctorName { get; set; }

        [Display(Name = "Doctor Email")]
        public string DoctorEmail { get; set; }

        [Display(Name = "Doctor Account Name/ID")]
        public Nullable<int> AccountID { get; set; }

        [Display(Name = "Patient Name")]
        public string PatientName { get; set; }

        [Display(Name = "Patient Email")]
        public string PatientEmail { get; set; }

        [Display(Name = "Status")]
        public string BookingStatus { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
